export { default as Home } from './Home/Home'
export { default as Stocks } from './Stocks/Stocks'
export { default as StockDetails } from './Stocks/StockDetails'
export { default as Crypto } from './Crypto/Crypto'
export { default as CryptoDetails } from './Crypto/CryptoDetails'
export { default as Exchanges } from './Exchanges/Exchanges'
export { default as ExchangeDetails } from './Exchanges/ExchangeDetails'
export { default as Forex } from './Forex/Forex'